steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Pulling Maven cache..."
        gsutil -m cp -r gs://s224169428/maven_cache/.m2 /workspace/ || echo "No existing cache."

  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

  - name: 'docker/compose:1.29.2'
    args:
      - 'run'
      - '--rm'
      - '-e'
      - 'MAVEN_CONFIG=/workspace/.m2'
      - 'book-test-runner'
      - 'mvn'
      - 'test'

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', '/workspace/.m2', 'gs://s224169428/maven_cache/']

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

options:
  logging: CLOUD_LOGGING_ONLY
