steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Test Image'
    args: ['build', '-f', 'Dockerfile.test', '-t', 'gcr.io/$PROJECT_ID/book-test-image', '.']

  - name: 'gcr.io/$PROJECT_ID/book-test-image'
    id: 'Run Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        Xvfb :99 & sleep 2 && mvn clean test

  - name: 'gcr.io/$PROJECT_ID/book-test-image'
    id: 'Package App'
    args: ['mvn', 'package']

options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

    
