steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Attempting to pull Maven cache..."
        gsutil -m cp -r gs://s224169428/maven_cache/.m2 /workspace/ || echo "No cache found. Proceeding..."

  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

  - name: 'docker/compose:1.29.2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for book-test-runner to be ready..."
        for i in {1..30}; do
          docker exec book-test-runner curl -s http://localhost:8080/health && break
          echo "Still waiting... $i"
          sleep 2
        done
        echo "Running tests..."
        docker exec book-test-runner mvn -Dmaven.repo.local=/workspace/.m2 test


  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', '/workspace/.m2', 'gs://s224169428/maven_cache/']

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

options:
  logging: CLOUD_LOGGING_ONLY
