steps:
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']
    dir: '.' 

  - name: 'docker/compose:1.29.2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker exec book-test-runner mvn test

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

options:
  logging: CLOUD_LOGGING_ONLY
