steps:
  # Pull Maven cache
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Pulling Maven cache..."
        gsutil -m cp -r gs://s224169428/maven_cache/.m2 /workspace/ || echo "No existing cache."

  # Start services and build images
  # - name: 'docker/compose:1.29.2'
  #   args: ['up', '-d', '--build']

  # Run integration tests
  # - name: 'docker/compose:1.29.2'
  #   args:
  #     - 'run'
  #     - '--rm'
  #     - '-e'
  #     - 'MAVEN_CONFIG=/workspace/.m2'
  #     - 'book-test-runner'
  #     - 'mvn'
  #     - 'test'

  # Save Maven cache
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['-m', 'cp', '-r', '/workspace/.m2', 'gs://s224169428/sit707/maven_cache/']

  # Clean existing target folder
  - name: 'gcr.io/cloud-builders/mvn'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Cleaning up target directory..."
        rm -rf target

  # Package JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package', '-DskipTests=true']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/book-app:latest', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/book-app:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'book-app'
      - '--image=gcr.io/$PROJECT_ID/book-app:latest'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']
