steps:
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

  - name: 'docker/compose:1.29.2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Waiting for services to start..."
        sleep 15
        echo "Running tests..."
        docker exec book-test-runner mvn -Dmaven.repo.local=/cache/.m2 test

volumes:
  - name: 'm2-cache'
    path: /cache/.m2

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

options:
  logging: CLOUD_LOGGING_ONLY
