steps:
  # Step 0: Install Chrome + ChromeDriver + Xvfb
  - name: 'ubuntu'
    id: 'Install Chrome & ChromeDriver'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget unzip gnupg curl xvfb \
        && curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux.gpg \
        && echo "deb [signed-by=/usr/share/keyrings/google-linux.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
        && apt-get update && apt-get install -y google-chrome-stable \
        && wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/136.0.7103.113/linux64/chromedriver-linux64.zip \
        && unzip chromedriver-linux64.zip && mv chromedriver-linux64/chromedriver /usr/bin/chromedriver && chmod +x /usr/bin/chromedriver



  # Step 1: Clean and compile
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Clean and Compile'
    args: ['clean', 'compile']

  # Step 2: Run tests with Xvfb + ChromeDriver
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Run Tests with Selenium'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        Xvfb :99 & export DISPLAY=:99 && mvn test

  # Step 3: Package the application
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Package App'
    args: ['package']

  # Optional: Deploy to App Engine or Cloud Run
  # If deploying to App Engine:
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   id: 'Deploy to App Engine'
  #   args: ['app', 'deploy']
  #   dir: 'path/to/your-app-engine-config'
options:
  logging: CLOUD_LOGGING_ONLY

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

