steps:
  # Step 1: Start Selenium Standalone Chrome (Dockerized)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Start Selenium Chrome'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker run -d -p 4444:4444 --shm-size=2g --name selenium selenium/standalone-chrome
        sleep 10  # Give time for Selenium server to start

  # Step 2: Run Tests using RemoteWebDriver
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Run Tests'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running Selenium tests using RemoteWebDriver..."
        mvn test

  # Step 3: Package application
  - name: 'gcr.io/cloud-builders/mvn'
    id: 'Package'
    args: ['package']

artifacts:
  objects:
    location: 'gs://s224169428/sit707/'
    paths: ['target/*.jar']

options:
  logging: CLOUD_LOGGING_ONLY
