FROM maven:3.9-eclipse-temurin-17

RUN apt-get update && apt-get install -y \
    wget unzip curl gnupg xvfb \
    libgtk-3-0 libnss3 libxss1 libasound2t64 libx11-xcb1 libdbus-1-3 \
    libxcomposite1 libxdamage1 libxrandr2 xdg-utils

# Install Chrome
RUN wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chrome-linux64.zip && \
    unzip chrome-linux64.zip && \
    mv chrome-linux64 /opt/chrome && \
    ln -s /opt/chrome/chrome /usr/bin/google-chrome && \
    rm chrome-linux64.zip

# Install Chromedriver
RUN wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip && \
    unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver && \
    mv chromedriver /usr/bin/chromedriver && \
    chmod +x /usr/bin/chromedriver && \
    rm chromedriver-linux64.zip

ENV DISPLAY=:99
