version: "3.9"
services:
  selenium:
    image: selenium/standalone-chrome:4.14.1
    ports:
      - "4444:4444"
    shm_size: "2g"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  book-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      selenium:
        condition: service_healthy
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    ports:
      - "8080:8080" 
