version: "3"
services:
  selenium:
    image: selenium/standalone-chrome:4.14.1
    ports:
      - "4444:4444"
    shm_size: "2g"

  book-test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - selenium
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
