FROM eclipse-temurin:17-jdk

RUN apt-get update && apt-get install -y \
    maven xvfb wget unzip curl gnupg \
    libgtk-3-0 libnss3 libxss1 libasound2t64 libx11-xcb1 libdbus-1-3 \
    libxcomposite1 libxdamage1 libxrandr2 xdg-utils
	
WORKDIR /app
COPY . .

# Start the app when container runs
CMD ["mvn", "spring-boot:run"]